### ISSUE TITLE
Improve front-end and UI

### ISSUE THREAD

**Issue by sunilsj99** [sunilsj99/WikipediaViewer#1]
Improve the front end and UI of both search page and result page

**Comment by tonp** [comment]
I'll like to work on this :)

**Comment by gelder-ux** [comment]
I'd also like to help! :)

**Comment by Shubham-SK** [comment]
I can also help, are you looking for anything in particular?

**Comment by sunilsj99** [comment]
@altruisticnarcissist Can you change the colour scheme to darker. Use some attractive colours.
